### PR TITLE
[XNIO-385] Ensure that the close method waits until the server key ca…

### PR DESCRIPTION
**Pull request by yersan**
…ncellation releases the resources

Follows up on #248 which was closed due to CI issues. However, I'm unable to see the issues again, and WildFly and WildFly Core testsuite pass with 3.8.x plus this patch.

Jira issue: https://issues.redhat.com/browse/XNIO-385
3.x PR: #310
3.9 PR: #325 

CC @fl4via

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]

**Comment by dmlloyd** [comment]
The change looks good to me, but again we'll want to check WildFly on all supported OSes to make sure there isn't some sneaky behavior (which sometimes there is with NIO).

**Comment by fl4via** [comment]
> The change looks good to me, but again we'll want to check WildFly on all supported OSes to make sure there isn't some sneaky behavior (which sometimes there is with NIO).

Ok, @dmlloyd that's a good point. I will run the suggested tests and I'll post a link here so we can fully validate the PR and merge it

**Comment by fl4via** [comment]
> > The change looks good to me, but again we'll want to check WildFly on all supported OSes to make sure there isn't some sneaky behavior (which sometimes there is with NIO).
> 
> Ok, @dmlloyd that's a good point. I will run the suggested tests and I'll post a link here so we can fully validate the PR and merge it

Working on this today

**Comment by fl4via** [comment]
> > > The change looks good to me, but again we'll want to check WildFly on all supported OSes to make sure there isn't some sneaky behavior (which sometimes there is with NIO).
> > 
> > 
> > Ok, @dmlloyd that's a good point. I will run the suggested tests and I'll post a link here so we can fully validate the PR and merge it
> 
> Working on this today

Here is the check: https://github.com/fl4via/xnio/actions/runs/8690905952
There are some failures, all of which seem unrelated.

**Pull request merged**
