### PR TITLE
Mainly contains the fix to XNIO-244, plus a minor test fix.

### PR DESCRIPTION
**Pull request by fl4via**

### CODE REVIEW

**Comment by eugeis** [comment]
Hi,
I am using WildFly 8.2 and we have same ploblem.
WildFly 8.2 is using xnio 3.3.0 and there are big differences to your fix.
Would you like to give me a hint, which classes (org.xnio.ssl.JsseSslStreamSourceConduit.java? ) in xnio 3.3.0 shall be fixed and how?
Or is it possible to use 3.4.beta2 in WildFly 8.2?
Thank You

**Comment by fl4via** [comment]
Hi, I'll take a look at porting the fix to the 3.3 branch.

**Comment by eugeis** [comment]
Thank you very much!

**Comment by fl4via** [comment]
I cant reproduce the bug with 3.3. Whatever bug you're seeing, it is not the same.
I followed the steps in the Jira (https://issues.jboss.org/browse/XNIO-244) to try to reproduce the bug with 3.3.
Please, give it a try with 3.4Beta and let me know if you still have problems.

**Pull request merged**
