### PR TITLE
[XNIO-353][JBEAP-17775] WARN message for rejected connections

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.jboss.org/browse/JBEAP-17775

### CODE REVIEW

**Comment by ivassile** [comment]
JBEAP(7.2.z): https://issues.jboss.org/browse/JBEAP-17775 (resolved with PR https://gitlab.cee.redhat.com/xnio/xnio/merge_requests/212 )
JBEAP(7.3.z): https://issues.jboss.org/browse/JBEAP-17860
Upstream: https://issues.jboss.org/browse/XNIO-353

**Comment by fl4via** [comment]
@aogburn how will this limit be configured in the server?

**Comment by dmlloyd** [comment]
I just want to note that this change might not be necessary in light of the fact that this TCP server is no longer the default.

**Comment by fl4via** [comment]
thanks for the reminder, @dmlloyd !
In fact, the QueuedNIoTcpServer2 is the default server now. We need to have this verified: is this change needed in the new server? @ivassile @aogburn

**Comment by dmlloyd** [comment]
The new server does not reject connections so there would be nothing to log at that point.  It's possible that it might benefit from some other, as-yet-unknown diagnostics.

**Comment by ivassile** [comment]
@fl4via We can probably close https://issues.jboss.org/browse/XNIO-353 and this PR. I opened PR [1] for  3.7.6.SP branch to replace it.

[1] https://gitlab.cee.redhat.com/xnio/xnio/merge_requests/212

**Comment by fl4via** [comment]
@ivassile Thanks, I'm closing this PR and I merged the one to gitlab.

**Comment by fl4via** [comment]
I am reopening it given discussion in Jira. We are not only adding this warning, as we are adding a warning for when the connection limit is reached in the new server class as well.

**Review by dmlloyd — APPROVED** [review]

**Pull request merged**
