### PR TITLE
[XNIO-317] Introduce API to clean ThreadLocal caches from ByteBufferSlicePool

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/XNIO-317

### CODE REVIEW

**Comment by iweiss** [comment]
Hi @dmlloyd, can this be merged and released as well, please?

**Comment by dmlloyd** [comment]
Did we have a discussion about this?  Normally I don't introduce new or change existing APIs in a minor branch.

**Comment by iweiss** [comment]
We did last year and the change ended up in 3.7 instead of 3.6

**Comment by xstefank** [comment]
@fl4via @dmlloyd this is the same change as is merged in 3.x (https://github.com/xnio/xnio/pull/142). This seems to be blocking https://github.com/undertow-io/undertow/pull/604. Can this be merged, please?

**Comment by dmlloyd** [comment]
As I said, we don't normally merge new APIs into old branches.  Can we upgrade to a 3.7 release instead?

**Comment by bmaxwell** [comment]
@dmlloyd  / @xstefank  , @fl4via  had mentioned moving xnio to 3.7 related to some performance issues, do we expect any issues going from 3.6 to 3.7 in EAP 7.2.z ? If not, then we just need to make sure QE is ok with it.

**Comment by mackaypeter** [comment]
We did some pre-testing with 3.7 and didn't really see any issues. @fl4via, was there anything in particular you were worried about?

**Comment by fl4via** [comment]
@mackaypeter the only concern about upgrading to XNIO 3.7.2.Final is that it requires jboss-remoting 5.0.12.Final to prevent a deadlock (REM3-336)

**Comment by fl4via** [comment]
@mackaypeter btw, I advise the upgrade to XNIO 3.7.2.Final and jboss remoting because of several issues that had been fixed. I'm tagging jboss-remoting today

**Comment by fl4via** [comment]
@xstefank the problem with this PR are the comments in the undertow PR by @msfm , that are correct. I'm going to review the whole solution from the xnio and undertow pov and get a final solution for these issues

**Comment by xstefank** [comment]
@fl4via thank you. I just want to mention that EAP 7.2.x is already on remoting 5.0.12 (https://github.com/jbossas/wildfly-core-eap/blob/6.0.x/pom.xml#L178)

**Comment by fl4via** [comment]
Closing this because the API doest not apply to old branch

**Pull request closed without merging**
