### PR TITLE
[XNIO-331] Implement XnioWorkerMXBean.getWorkerPoolSize

### PR DESCRIPTION
**Pull request by carterkozak**

### CODE REVIEW

**Comment by dmlloyd** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by carterkozak** [comment]
> We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

I do.

**Comment by dmlloyd** [comment]
Yeah this no longer compiles.

**Comment by dmlloyd** [comment]
Thanks for the contributions.

**Pull request merged**
