### PR TITLE
[XNIO-275] Work around HP-UX sleep problem

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@dmlloyd is there some more info about this ? Is the effect that it may never unblock at all from select() ?

**Comment by dmlloyd** [comment]
Yes @normanmaurer - I think it's related to waiting for write events when a socket is closed at an unfortunate time, but I'm not certain, and I don't have adequate resources to thoroughly test.  This is certainly nothing more than an ugly workaround, but it seems to make the immediate problem go away.

**Comment by normanmaurer** [comment]
@dmlloyd interesting... If you ever get more infos I would be interested to hear about it. Would also be interesting to know which JVM they are using (and which version).

**Comment by dmlloyd** [comment]
I believe HP UX does their own builds of the Oracle JDK.  It's some recent-ish 1.8 version.

**Comment by normanmaurer** [comment]
@dmlloyd thanks!

**Pull request merged**
