### PR TITLE
[XNIO-387] IoUtils#safeClose Enhancement

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/XNIO-387

### CODE REVIEW

**Comment by boris-unckel** [comment]
Hello @dmlloyd @fl4via I have written a short enhancement proposal in Jira, this is the way I would implement the others also. I would like to get feedback first before I continue. 

I would like to extend safeClose for the following classes:
- javax.xml.stream.XMLStreamReader (sample here)
- javax.xml.stream.XMLStreamWriter (sample here)
- javax.xml.stream.XMLEventReader
- javax.xml.stream.XMLEventWriter
- javax.naming.Context
- javax.naming.NamingEnumeration

Too much? A class missing?

**Comment by dmlloyd** [comment]
I would be inclined to say "no": JAXP (XML) and JNDI are out of scope for XNIO.

**Comment by boris-unckel** [comment]
@dmlloyd Yes, in terms of scope I agree. From a users perspective you've to switch between different APIs, have more than one dependency.  XMLStreamReader/Writer does not close recursively the underlying stream. Mixing up try-with-resources and a finally safeClose and getting IOExceptions in one case and a trace-log-entry in the other?
All other implementations suffer from different issues and/or are not good in terms of dependencies.

(Still hoping to convince you :-) )

**Comment by boris-unckel** [comment]
Different approach: safeClose(Object resource) and a reflection based "close" call?

**Comment by dmlloyd** [comment]
Here's something you can always do though, with any class that has a "close" (or similar) method:

```java
XMLStreamReader xsr = ...;
safeClose((Closeable) xsr::close);
```

**Comment by boris-unckel** [comment]
@dmlloyd This would be an excellent workaround but the close method throws a checked exception. Is there a common functional container, calling a method and re-throwing checked as unchecked exceptions?

**Comment by carterkozak** [comment]
```diff
- safeClose((Closeable) xsr::close);
+ safeClose((AutoCloseable) xsr::close);
```

**Comment by dmlloyd** [comment]
The `safeClose` method does not throw any exceptions, and the point of it is to absorb checked exceptions. So you would cast your method handle based on the kind of exception that you expect it to throw; `IOException` is the most common, but I guess XML streams throw `XMLStreamException` or something like that so you'd have to do what @carterkozak just suggested and use the `AutoCloseable` interface instead, which really covers pretty much every case.

**Comment by boris-unckel** [comment]
@carterkozak @dmlloyd Thanks - this is great! I think it's still very readable and easy to maintain.

**Pull request closed without merging**
